### PR TITLE
Add a seventh service port

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This is for the new secondary https port added to WPT; see
https://github.com/web-platform-tests/wpt.live/issues/32

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@jugglinmike - let me know if you'd rather we just fork this repo into github.com/ecosystem-infra, happy to do that instead.

**Comment by jugglinmike** [comment]
Yeah, that seems like the best way to make sure you get timely review. Not sure how much you care about the lineage, but that will make your repo a fork-of-a-fork-of-a-fork. We could transfer this if you prefer.

**Comment by stephenmcgruer** [comment]
A transfer would be great, if y'all aren't using it. Transfer to https://github.com/Ecosystem-Infra/ please :)

**Comment by jugglinmike** [comment]
When I attempt to transfer, GitHub reminds me that I don't have permission to create public repositories in that Organization. I've sent you a request to become an administrator of this repository. That ought to be sufficient to allow you to transfer it to the new Organization.

**Comment by stephenmcgruer** [comment]
Awesome, I've done the transfer and updated wpt.live's terraform file to point to this repo. Thanks Mike!

**Comment by jugglinmike** [comment]
Sure thing :)

**Review by Hexcles — APPROVED** [review]
LGTM

And TIL how this is set up...

**Comment by jugglinmike** [comment]
@Hexcles I'd be interested to hear your thoughts as a long-time sysadmin about Terraform's approach to infrastructure-as-code.

**Pull request merged**
